name: CI/CD Pipeline 
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-push:
    name: CI - Build and Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3
      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build y Push de la imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aliciasp2004/actividad61-aplicacion-crud-php:latest
  deploy: 
    name: CD - Deploy
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Ejecutar comandos remotos por SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/actividad61-aplicacion-php-produccion
            docker-compose pull
            docker-compose up -d --force-recreate
            docker image prune -f
